apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlite-db-deployment
  labels:
    app: sqlite-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlite-db
  template:
    metadata:
      labels:
        app: sqlite-db
    spec:
      containers:
      - name: sqlite-db
        image: rhythm12/user_email_management-sqlite-db
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: db-volume
          mountPath: /data
        command:
        - sh
        - -c
        - |
          sqlite3 /data/data.db "CREATE TABLE IF NOT EXISTS email_table (id INTEGER PRIMARY KEY, email TEXT UNIQUE);" && tail -f /dev/null
      volumes:
      - name: db-volume
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: sqlite-db-service
  labels:
    app: sqlite-db
spec:
  selector:
    app: sqlite-db
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  clusterIP: None  # Use a headless service for direct Pod-to-Pod communication