apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-app-deployment
  labels:
    app: streamlit-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit-app
  template:
    metadata:
      labels:
        app: streamlit-app
    spec:
      containers:
      - name: streamlit-app
        image: rhythm12/user_email_management-streamlit-app
        ports:
        - containerPort: 8501
        envFrom:
        - configMapRef:
            name: app-config  # Reference the ConfigMap
---
apiVersion: v1
kind: Service
metadata:
  name: streamlit-app-service
  labels:
    app: streamlit-app
spec:
  selector:
    app: streamlit-app
  ports:
  - protocol: TCP
    port: 8501
    targetPort: 8501
  type: LoadBalancer