apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: emailapp
spec:
  # 3 Pods should exist at all times.
  replicas: 3
  selector:
    matchLabels:
      app: emailapp
  template:
    metadata:
      labels:
        # Apply this label to pods and default
        # the Deployment label selector to this value
        app: emailapp
    spec:
      containers:
      - name: emailapp
        # Run this image
        image: rhythm12/user_email_management
---
kind: Service
apiVersion: v1
metadata:
  # Unique key of the Service instance
  name: service-app
spec:
  ports:
    # Accept traffic sent to port 80
    - name: http
      port: 8501
      targetPort: 8501
  selector:
    # Loadbalance traffic across Pods matching
    # this label selector
    app: emailapp
  # Create an HA proxy in the cloud provider
  # with an External IP address - *Only supported
  # by some cloud providers*
  type: LoadBalancer