name: Publish Docker Image

on:
  push:
    tags:
      - "*"  # Trigger on any new tag

jobs:
  build-and-publish:
    runs-on: self-hosted

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Set this in repository secrets
        password: ${{ secrets.DOCKER_PASSWORD }}  # Set this in repository secrets

    # Build and tag the Docker image
    - name: Build Docker Image
      run: |
        IMAGE_NAME=rhythm12/user_email_management
        TAG=${GITHUB_REF##*/}
        docker build -t $IMAGE_NAME:$TAG -f streamlit_app/Dockerfile .

    # Push the Docker image
    - name: Push Docker Image
      run: |
        IMAGE_NAME=rhythm12/user_email_management
        TAG=${GITHUB_REF##*/}
        docker push $IMAGE_NAME:$TAG
